version: "3.8"
services:
  db:
    image: postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '4'
          memory: 2G

    environment:
      POSTGRES_DB: thesis
      POSTGRES_USER: thesis
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"